// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	// Входные данные: customer_id = 42
	// Выходные данные: {id: 1, customer_id: 42, created_at: '2024-01-15 10:30:00'}
	CreateOrder(ctx context.Context, customerID int64) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	FindPoductsByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	UpdateProductQuantity(ctx context.Context, arg UpdateProductQuantityParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
